# App info
spring.application.name=mc

# Server config
server.port=8080

# Logging
logging.level.root=INFO
logging.level.it.cnr.istc.pst.mc=INFO

# Scheduler
spring.task.scheduling.pool.size=2

# Ontology model to use
mc.ontology-path=src/main/resources/onto/mobipick_uc1_v#VER#.rdf
mc.ontology-version=0.1
mc.ontology-format=RDF/XML
mc.rules-path=src/main/resources/onto/cognition.rules


# Scenario UC1
mc.kg-uc1=src/main/resources/onto/mobipick_uc1_v#VER#.rdf
# Sementics
mc.ontology-base=src/main/resources/onto/metacog_v#VER#.rdf



