PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dul: <http://www.loa-cnr.it/ontologies/DUL.owl#>
PREFIX soho: <http://pst.istc.cnr.it/ontologies/2019/01/soho#>
PREFIX mc: <http://pst.istc.cnr.it/ontologies/2026/metacognition#>

SELECT ?l ?s ?x ?y ?z
WHERE {
 ?l rdf:type mc:EnvironmentLocation .
 ?l soho:hasLabel ?s .
 ?l dul:hasQuality ?p .
 ?p dul:hasRegion ?r .
 ?r rdf:type mc:DiscretePoseRegion .
 ?r mc:hasCoordinateX ?x .
 ?r mc:hasCoordinateY ?y .
 ?r mc:hasCoordinateZ ?z .
}
